name: monodepth2
dependencies:
    - pytorch
    - torchvision
    - pip
    - pip:
        - tensorboardX
        - scikit-image
        - tqdm
        - tensorboard
        - ipython
    - opencv=3.3.1
